"""deleted op

Revision ID: d354fd98ff7b
Revises: ff0271c6d3b7
Create Date: 2019-12-18 20:20:08.638048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd354fd98ff7b'
down_revision = 'ff0271c6d3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_column('op')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('op', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###
