"""added op

Revision ID: ff0271c6d3b7
Revises: 06df7fe36d07
Create Date: 2019-12-18 15:31:56.440510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0271c6d3b7'
down_revision = '06df7fe36d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('op', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'op')
    # ### end Alembic commands ###
